name: dask-expr
channels:
  - conda-forge
dependencies:
  - pytest
  - pytest-cov
  - pytest-xdist
  - dask  # overridden by git tip below
  - pyarrow>=7
  - pandas>=2
  - pre-commit
  - pip:
    - git+https://github.com/fjetter/distributed@expr_to_scheduler_v2
    - git+https://github.com/fjetter/dask@expr_to_scheduler_v2
